Hw 1
Batmaev/2019-2-Track-Frontend-V-Batmaev pull request #1
Opened 2019-10-07 18:34 UTC by Batmaev

# Домашнее задание №1

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
* Все три функции
* Тест для функции convertToHuman
* Я невнимательно прочитал условие и расширил тесты для других функций

Функция convertBytesToHuman как-то слишком хорошо проходит тест

2019-10-07 20:23 UTC, chexex requested changes
Необходимо связать репозиторий со сборщиком (travis-ci.org)
Помогут последние слайды с первой лекции.
После того, как репозиторий будет добавлен в сборку, необходимо будет выполнить любой коммит и запушить изменения, чтобы стартануть сборку.

2019-10-08 07:46 UTC, chexex requested changes
1. разделить пулл реквесты на первое и на второе дз
2. Удалить лишние/отладочные файлы (.vscode, a.html)
3. поправить [.travis.yml](https://github.com/Batmaev/2019-2-Track-Frontend-V-Batmaev/blob/hw_2/.travis.yml#L8-L11)
```js
  - npm run test
  - npm run build
```

2019-10-08 07:46 UTC, chexex commented on web-components/package.json
> +    "test:coverage": "npm test --coverage",
Для второго задания здесь нужно будет только линтер прогонять (eslint .)

2019-10-08 16:37 UTC, Batmaev commented on web-components/package.json
> +    "test:coverage": "npm test --coverage",
Прогнать линтер по шестой и седьмой строчке? Добавить в web-components/package.json что-то вроде этого, по аналогии с package.json вне web-components? Что-то другое?
```suggestion
"scripts": {
    ...
    "lint": "npm run lint:js && npm run lint:dup && npm run lint:css",
    "lint-fix": "eslint --fix",
...
} 
```

2019-10-09 18:43 UTC, chexex approved these changes
**Учесть комменты при выполнении второго дз**

Функции +
Тесты +
Сборка +

Спасибо за работу,
12 баллов

2019-10-09 18:43 UTC, chexex commented on web-components/package.json
> +    "test:coverage": "npm test --coverage",
1. В веб компонентах нет реакта и реакт-скриптов :)
2. Этот файл для первого дз можно вообще не трогать
3. `npm run lint:js`, `npm run lint:dup`, `npm run lint:css` подразумевают, что у тебя описаны инструкции для `lint:js`, `lint:dup` и `lint:css`
```js
// ...
  "lint:js": ...
  "lint:dup": ...
  "lint:css": ...
// ...
```

2019-10-09 18:44 UTC, merged