Hw 2
Batmaev/2019-2-Track-Frontend-V-Batmaev pull request #2
Opened 2019-10-14 15:06 UTC by Batmaev

# Домашнее задание № 2

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
* При отправке сообщение показывается на экране и сохраняется в Local Storage
* При запуске читается Local Storage

2019-10-15 13:15 UTC, priver requested changes
Нужно выкатить на github pages, сейчас там ничего не работает

2019-10-15 16:01 UTC, priver requested changes

2019-10-15 16:01 UTC, priver commented on web-components/src/components/MessageForm.js
> +        localStorage.setItem(localStorage.length/3 + 1 + "time", new Date());
ужас какой то, никогда так больше не делай.

localStorage.length - это общее количество элементов, а не только те которые ты записал в этой функции

```js
4 / 3 + 1 + 'time' // "2.333333333333333time"
```
нужно просто записать в storage массив объектов в один ключ.

2019-10-15 16:01 UTC, priver commented on web-components/src/index.html
> +        localStorage.setItem(localStorage.length + 1 + "text", "Example")
инлайн-скриптов быть не должно

2019-10-15 16:01 UTC, priver commented on web-components/src/index.js
> +import './components/ExistingMessage';
импорт message-from должен быть последним (т.к. иначе в момент его вызова остальные custom element'ы еще не будут инициализированы)

2019-10-15 16:34 UTC, Batmaev commented on web-components/src/components/MessageForm.js
> +        localStorage.setItem(localStorage.length/3 + 1 + "time", new Date());
Действительно)
Я заметил, что оно плохо работает, и сделал лучше. Но всё равно с тремя типами ключей, потому что тогда ещё не увидел ваш комментарий

2019-10-15 18:40 UTC, priver commented on web-components/src/components/MessageForm.js
> +        localStorage.setItem(localStorage.length/3 + 1 + "time", new Date());
сделай массив!)

2019-10-16 10:56 UTC, priver requested changes

2019-10-16 10:56 UTC, priver commented on web-components/src/ReadStorage.js
> +        }
отформатируй по человечески. такой код невозможно читать.
в требованиях к ДЗ была проверка кода линтером

2019-10-16 10:56 UTC, priver commented on web-components/src/components/ExistingMessage.js
> +}
аналогично. в таком виде я это проверять не буду

2019-10-18 17:38 UTC, Batmaev commented
Странно, на localhost работает, а на gh-pages в localStorage ничего не сохраняется

2019-10-21 09:40 UTC, priver requested changes
- не нужно отправлять пустые сообщения
- доскролливать до последнего сообщения при отправке

2019-10-21 09:40 UTC, priver commented on web-components/src/components/ExistingMessage.js
> +<div id="text in message" class="main_text"></div>
в id не должно быть пробелов

2019-10-21 09:40 UTC, priver commented on web-components/src/components/ExistingMessage.js
> +            styles.insertAdjacentHTML("afterbegin", `
нужно просто добавить отправленному сообщению класс, а не вставлять кучу стилей. стили для класс добавить в тэг style в шаблоне

2019-10-21 09:40 UTC, priver commented on web-components/src/ReadStorage.js
> +let number_of_messages = localStorage.getItem("Number of messages")
нужно сохранять сообщения в массив, а массив целиком записывать в localStorage в один ключ.

2019-10-24 06:53 UTC, chexex commented
Внешний вид +
Функционал +
Сборка +


@priver меня, в целом, устраивает, если не обращать внимание на формат времени
![image](https://user-images.githubusercontent.com/16698238/67460588-098dae80-f644-11e9-974d-762d884414c9.png)

2019-10-24 10:34 UTC, priver approved these changes
10 баллов

2019-10-24 10:34 UTC, merged