Hw 3
Batmaev/2019-2-Track-Frontend-V-Batmaev pull request #3
Opened 2019-10-26 20:39 UTC by Batmaev

# Домашнее задание №3

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
* Список чатов
* Переход от списка чатов к сообщениям и обратно
* Некоторые иконки

2019-10-27 11:00 UTC, martinkomitsky requested changes
Исправить замечания +, похоже, у тебя не был выполнен пункт про airbnb конфиг для линтера из дз2. Очень нужно его выполнить, это сделает немного читабельней твой код

2019-10-27 11:00 UTC, martinkomitsky commented on web-components/src/index.js
> +import "./components/MessageList"
Не совсем понятно, как линтер такое пропустил. Должен быть выбран один тип кавычек

2019-10-27 11:00 UTC, martinkomitsky commented on web-components/src/components/MessageForm.js
> +            if(minutes < 10) minutes = `0${  minutes}`;
тут тоже очень похоже на то, что линтер не отработал. Запускал его, вообще?

2019-10-27 11:00 UTC, martinkomitsky commented on web-components/src/components/ChatList.js
> +   <chat-in-chat-list chat_id="7"></chat-in-chat-list>
Почему бы тут в цикле не вывести все имеющиеся чаты? При создании нового чата, если обновить страничку, он не появляется, хоть и присутствует в LS

2019-10-27 17:50 UTC, Batmaev commented on web-components/src/components/MessageForm.js
> +            if(minutes < 10) minutes = `0${  minutes}`;
Я не понимаю, как им пользоваться. В VSCode есть что-то типа линтера, он показывает ошибки из серии "Здесь строка завершается как CRLF, а надо LF". Я попробовал сейчас удалить package-lock и изменить dev-dependecies в package.json, как Алексей Опалев когда-то давно писал в чате. Теперь при запуске eslint возникают ошибки, и Трэвис не собирается 

The following rules are unnecessary or might conflict with Prettier:        

- semi
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! track-mail-2019@0.1.0 eslint-check: `eslint --print-config .eslintrc.js | eslint-config-prettier-check`  
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the track-mail-2019@0.1.0 eslint-check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Василий\AppData\Roaming\npm-cache\_logs\2019-10-27T17_49_08_641Z-debug.log
Процесс терминала завершен с кодом выхода: 1

2019-10-28 04:43 UTC, martinkomitsky commented on web-components/src/components/MessageForm.js
> +            if(minutes < 10) minutes = `0${  minutes}`;
> про часы и минуты?

```if (minutes < 10) {
  minutes = `0${  minutes}`;
}```


> В VSCode есть что-то типа линтера

Да, есть. Но в проект надо добавить автоматическую проверку кодстайла, путем добавки eslint и соответствующего для него конфига, который указан в условии дз

>Трэвис сначала ругался на package-lock.json, а сейчас он не может найти copy-webpack-plugin.

@chexex посмотришь, что тут не так?

2019-10-28 04:45 UTC, martinkomitsky requested changes
Разбираемся с линтером и ждем хелпа от @chexex

2019-10-28 07:51 UTC, chexex commented on .editorconfig
> -end_of_line = lf
почему?

2019-10-28 07:51 UTC, chexex commented on .gitignore
> +web-components/src/chats.html
почему?

2019-10-28 07:51 UTC, chexex commented on .travis.yml
> +  - npm install copy-webpack-plugin --save-dev
так нельзя, copy-webpack-plugin нужно унести в package.json (package-lock.json удалить из версионирования)

2019-10-28 07:51 UTC, chexex commented on web-components/src/ReadStorage.js
> +// window.scrollTo(0, messages.scrollHeight);
все, что не нужно, удалить из пулл реквеста (можно перенести в другую ветку, если код дорог)

2019-10-28 07:51 UTC, chexex commented on web-components/src/components/MessageForm.js
> +            if(minutes < 10) minutes = `0${  minutes}`;
посмотрел.

0. Убедиться, что в web-components/package.json указан нужный плагин
1. Удалить package-lock.json
2. Удалить ветку gh-pages, если не помогло

2019-10-28 08:15 UTC, Batmaev commented on .gitignore
> +web-components/src/chats.html
web-components/src/chats.html - это черновик списка чатов. Хорошо, я удалю его насовсем и уберу из gitignore

2019-10-28 08:17 UTC, Batmaev commented on .editorconfig
> -end_of_line = lf
Оно само... Я догадался вчера поменять на crlf

2019-10-28 08:43 UTC, Batmaev commented
Большое спасибо: теперь Трэвис находит копирующий плагин. Однако, он всё ещё показывает `npm ERR! missing script: eslint`. Я удалил gh-pages, и это не помогло.

2019-10-29 04:42 UTC, martinkomitsky commented on .editorconfig
> -end_of_line = lf
плагин в vscode должен смотреть в конфиг проекта, это надо донастроить. Возможно, поставить плагин editorconfig

2019-10-29 04:42 UTC, martinkomitsky approved these changes

2019-10-29 04:42 UTC, merged

2019-10-29 04:43 UTC, martinkomitsky commented
6